### ISSUE TITLE
1.0.3 doesn't work with OSX (10.9.4) - Symbol not found: _rb_id2sym

### ISSUE THREAD

**Issue by koseki** [tenderlove/syck#5]
```console
$ ruby -v -r syck -e 'p Syck::VERSION'
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.0.0]
dyld: lazy symbol binding failed: Symbol not found: _rb_id2sym
  Referenced from: /Users/koseki/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/syck-1.0.3/lib/syck.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_id2sym
  Referenced from: /Users/koseki/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/syck-1.0.3/lib/syck.bundle
  Expected in: flat namespace

zsh: trace trap  ruby -v -r syck -e 'p Syck::VERSION'
```

When I build `1.0.3` myself, it works fine.

```console
$ git checkout v1.0.3
$ rake install_gem
$ ruby -v -r syck -e 'p Syck::VERSION'
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin13.0.0]
"1.0.3"
```

Unpack both gem files and check diff:

```console
$ diff -r ./syck-1.0.3-dist/ ./syck-1.0.3/
Binary files syck-1.0.3-dist/lib/syck.bundle and syck-1.0.3/lib/syck.bundle differ
```

Is there something wrong with `syck.bundle` ?

I founded this issue, so this may not be my local problem.

 * https://github.com/instructure/i18nema/issues/4

**Comment by koseki** [comment]
#10 (`1.0.5`) fixed this issue. Thanks! @hsbt @sorah

**Comment by hsbt** [comment]
:octocat:
